# <u>HYPOTHESIS TESTING EXERCISE

# 


# Q1)  
# A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. A randomly selected sample of cutlets was collected from both units and measured? Analyze the data and draw inferences at 5% significance level. Please state the assumptions and tests that you carried out to check validity of the assumptions. 

# 

## Ans - 
## The assumption we will take here is 2 Sample T Test

# <u>Import Necessary Libraries - 

In [1]:
import pandas as pd
import seaborn as sns

from scipy import stats
import numpy as np

# <u>Import data : -

In [4]:
cutlets_data = pd.read_csv('Cutlets.csv')
cutlets_data

Unit A  Unit B
0   6.8090  6.7703
1   6.4376  7.5093
2   6.9157  6.7300
3   7.3012  6.7878
4   7.4488  7.1522
5   7.3871  6.8110
6   6.8755  7.2212
7   7.0621  6.6606
8   6.6840  7.2402
9   6.8236  7.0503
10  7.3930  6.8810
11  7.5169  7.4059
12  6.9246  6.7652
13  6.9256  6.0380
14  6.5797  7.1581
15  6.8394  7.0240
16  6.5970  6.6672
17  7.2705  7.4314
18  7.2828  7.3070
19  7.3495  6.7478
20  6.9438  6.8889
21  7.1560  7.4220
22  6.5341  6.5217
23  7.2854  7.1688
24  6.9952  6.7594
25  6.8568  6.9399
26  7.2163  7.0133
27  6.6801  6.9182
28  6.9431  6.3346
29  7.0852  7.5459
30  6.7794  7.0992
31  7.2783  7.1180
32  7.1561  6.6965
33  7.3943  6.5780
34  6.9405  7.3875

In [5]:
unit_a = cutlets_data[['Unit A']]
unit_a

Unit A
0   6.8090
1   6.4376
2   6.9157
3   7.3012
4   7.4488
5   7.3871
6   6.8755
7   7.0621
8   6.6840
9   6.8236
10  7.3930
11  7.5169
12  6.9246
13  6.9256
14  6.5797
15  6.8394
16  6.5970
17  7.2705
18  7.2828
19  7.3495
20  6.9438
21  7.1560
22  6.5341
23  7.2854
24  6.9952
25  6.8568
26  7.2163
27  6.6801
28  6.9431
29  7.0852
30  6.7794
31  7.2783
32  7.1561
33  7.3943
34  6.9405

In [6]:
unit_b = cutlets_data[['Unit B']]
unit_b

Unit B
0   6.7703
1   7.5093
2   6.7300
3   6.7878
4   7.1522
5   6.8110
6   7.2212
7   6.6606
8   7.2402
9   7.0503
10  6.8810
11  7.4059
12  6.7652
13  6.0380
14  7.1581
15  7.0240
16  6.6672
17  7.4314
18  7.3070
19  6.7478
20  6.8889
21  7.4220
22  6.5217
23  7.1688
24  6.7594
25  6.9399
26  7.0133
27  6.9182
28  6.3346
29  7.5459
30  7.0992
31  7.1180
32  6.6965
33  6.5780
34  7.3875

## <u>Hypothesis Formulation :
* **Ho: There is no difference in diameters of cutlets between two units.**
* **Ha: There is significant difference in diameters of cutlets between two units.**


In [7]:
t_val,p_val = stats.ttest_ind(a = unit_a , b = unit_b)
t_val,p_val

(array([0.72286887]), array([0.47223947]))

In [12]:
if p_val<0.05:
    print(' There is significant difference in diameters of cutlets between two units.')
else:
    print('There is no difference in diameters of cutlets between two units.')

 There is significant difference in diameters of cutlets between two units.


##  We do not  reject the null hypothesis.

# =========================================================== 

# Q2)
#    A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. They collected a random sample and recorded TAT for reports of 4 laboratories. TAT is defined as sample collected to report dispatch.
   
# Analyze the data and determine whether there is any difference in average TAT among the different laboratories at 5% significance level.

# <u>Import data : -

In [9]:
labtat_data = pd.read_csv('LabTAT.csv')
labtat_data

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0          185.35        165.53        176.70        166.13
1          170.49        185.91        198.45        160.79
2          192.77        194.92        201.23        185.18
3          177.33        183.00        199.61        176.42
4          193.41        169.57        204.63        152.60
..            ...           ...           ...           ...
115        178.49        170.66        193.80        172.68
116        176.08        183.98        215.25        177.64
117        202.48        174.54        203.99        170.27
118        182.40        197.18        194.52        150.87
119        182.09        215.17        221.49        162.21

[120 rows x 4 columns]

## The assumption we will take here is Annova Test.

## <u>Hypothesis Formulation :
* **Ho: No Varaince: All samples TAT population means are same.**
* **Ha: It has Variance: Atleast one sample TAT population mean is different.**


In [10]:
t_val,p_val = stats.f_oneway(labtat_data[['Laboratory 1']],labtat_data[['Laboratory 2']],labtat_data[['Laboratory 3']],
                             labtat_data[['Laboratory 4']])
t_val,p_val

(array([118.70421654]), array([2.11567089e-57]))

In [14]:
if p_val<0.05:
    print('It has Variance: Atleast one sample TAT population mean is different.')
else:
    print('No Varaince: All samples TAT population means are same.')

It has Variance: Atleast one sample TAT population mean is different.


## It has Variance: Atleast one sample TAT population mean is different. 

# =============================================================

# Q3)
#       Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.

# <u>Hypothesis Formulation :
* **Ho: All proportions are equal.**
* **Ha: Not all proportions are equal .**


# <u>Import data : -

In [12]:
buyer_ratio = pd.read_csv('BuyerRatio.csv')
buyer_ratio

Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [13]:
buyer_ratio = pd.pivot_table(data = buyer_ratio,columns = 'Observed Values')
buyer_ratio

Observed Values  Females  Males
East                 435     50
North               1356    131
South                750     70
West                1523    142

In [5]:
stats.chi2_contingency(observed = buyer_ratio)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[ 442.23468701,   42.76531299],
        [1355.88243213,  131.11756787],
        [ 747.69575948,   72.30424052],
        [1518.18712138,  146.81287862]]))

In [7]:
chi2_score,p_val,dof,expected = stats.chi2_contingency(observed = buyer_ratio)
print('***************************************************')
print('CHI-SQAURE TEST RESULTS')
print('Chi2 Value        : ',chi2_score)
print('P-value           : ',p_val)
print('Degree of Freedom : ',dof)
print('Expected Table    :\n',expected)
print('***************************************************')

***************************************************
CHI-SQAURE TEST RESULTS
Chi2 Value        :  1.595945538661058
P-value           :  0.6603094907091882
Degree of Freedom :  3
Expected Table    :
 [[ 442.23468701   42.76531299]
 [1355.88243213  131.11756787]
 [ 747.69575948   72.30424052]
 [1518.18712138  146.81287862]]
***************************************************


In [8]:
if p_val<0.05:
    print('Male - Female buyer rations are not similar across regions.')
else:
    print('Male - Female buyer rations are similar across regions.')

Male - Female buyer rations are similar across regions.


## Male - Female buyer rations are similar across regions. 

# =============================================================

# Q4)
#      TeleCall uses 4 centers around the globe to process customer order forms. They audit a certain %  of the customer order forms. Any error in order form renders it defective and has to be reworked before processing.  The manager wants to check whether the defective %  varies by centre. Please analyze the data at 5% significance level and help the manager draw appropriate inferences.

# <u>Hypothesis Formulation :
* **Ho: Independence of categorical variables (customer order forms defective % does not varies by centre).**
* **Ha:  Dependence of categorical variables (customer order forms defective % varies by centre) .**


# <u>Import data : -

In [2]:
customer_order_form = pd.read_csv('Costomer+OrderForm.csv')
customer_order_form

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [3]:
customer_order_form['Phillippines'].value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [4]:
customer_order_form['Indonesia'].value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [5]:
customer_order_form['Malta'].value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [6]:
customer_order_form['India'].value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [7]:
customer = {'Country' : ['Phillippines','Indonesia','Malta','India'],
            'Error Free' : [271,267,269,280],
            'Defective': [29,33,31,20]}

In [8]:
customer_data = pd.DataFrame(customer)
customer_data

Country  Error Free  Defective
0  Phillippines         271         29
1     Indonesia         267         33
2         Malta         269         31
3         India         280         20

In [13]:
customer_data = pd.pivot_table(data = customer_data,index='Country')
customer_data

Defective  Error Free
Country                            
India                20         280
Indonesia            33         267
Malta                31         269
Phillippines         29         271

In [14]:
stats.chi2_contingency(observed = customer_data)

(3.8589606858203545,
 0.2771020991233144,
 3,
 array([[ 28.25, 271.75],
        [ 28.25, 271.75],
        [ 28.25, 271.75],
        [ 28.25, 271.75]]))

In [15]:
chi2_score,p_val,dof,expected = stats.chi2_contingency(observed = customer_data)
print('***************************************************')
print('CHI-SQAURE TEST RESULTS')
print('Chi2 Value        : ',chi2_score)
print('P-value           : ',p_val)
print('Degree of Freedom : ',dof)
print('Expected Table    :\n',expected)
print('***************************************************')

***************************************************
CHI-SQAURE TEST RESULTS
Chi2 Value        :  3.8589606858203545
P-value           :  0.2771020991233144
Degree of Freedom :  3
Expected Table    :
 [[ 28.25 271.75]
 [ 28.25 271.75]
 [ 28.25 271.75]
 [ 28.25 271.75]]
***************************************************


In [16]:
if p_val<0.05:
    print(' Dependence of categorical variables (customer order forms defective % varies by centre).')
else:
    print('Independence of categorical variables (customer order forms defective % does not varies by centre).')

Independence of categorical variables (customer order forms defective % does not varies by centre).


## Independence of categorical variables (customer order forms defective % does not varies by centre) 